modified   centos-installScript modified   centos7-installScript modified   fedora-installScript modified   ubuntu-installScript

diff --git a/centos7-installScript b/centos7-installScript
--- a/centos7-installScript
+++ b/centos7-installScript
@@ -7,30 +7,110 @@
 
 function showMenu()
 {
+	setupLibs
 	clear
 	echo
 	echo "--------------------------------------------------------------"
 	echo "|      Centos7 Install Helper                                |"
 	echo "|      copyright https://github.com/cjy37                    |"
 	echo "--------------------------------------------------------------"
-	echo "|      a. Install Web Server + MySQL [d,e,g,h,k,l]           |"
-	echo "|      b. Install Web Server   [d,e,g,k,l]                   |"
-	echo "|      c. Install MySQL    [d,h,l]                           |"
-	echo "|      d. Install Libs     [Public Libs]                     |"
-	echo "|      e. Install mono                                       |"
-	echo "|      f. Install Nodejs                                     |"
-	echo "|      g. Install jexus v5                                   |"
-	echo "|      h. Install mysql v5.5                                 |"
-	echo "|      i. Install memcached                                  |"
-	echo "|      j. Install nginx                                      |"
-	echo "|      k. Install haproxy                                    |"
-	echo "|      l. Install Redis                                      |"
-	echo "|      m. Install CutyCapt                                   |"
-	echo "|      n. Install GtkSharp                                   |"
-	echo "|      o. Install MongoDB                                    |"
+	echo "|      a. Install ALL                                        |"
+	echo "|      b. Install Web Server (linux mono mysql jexus)[c,d]   |"
+	echo "|      c. Install Mono & Jexus (Asp.Net Web Server)          |"
+	echo "|      d. Install Mysql (MariaDB-10)                         |"
+	echo "|      e. Install Haproxy                                    |"
+	echo "|      f. Install Redis                                      |"
+	echo "|      g. Install Node.js                                    |"
+	echo "|      h. Install MongoDB                                    |"
+	echo "|      i. Install Nginx                                      |"
+	echo "|      j. Install Memcached                                  |"
+	echo "|      k. Install CutyCapt                                   |"
+	echo "|      l. Install GtkSharp                                   |"
 	echo "|      x. Exit                                               |"
 	echo "--------------------------------------------------------------"
 	echo
+	return 0
+}
+
+function selectCmd()
+{
+	alias cp='cp'
+	showMenu
+	echo "Please select a serial number for installation [a-x]:"
+	read -n 1 M
+	echo
+
+	if [ "$M" = "x" ]; then
+		exit 1
+		
+	elif [ "$M" = "a" ]; then
+		echo "Installing ALL..."
+		echo "------------------------------------"
+		setupMono
+		setupMysql
+		setupHaproxy
+		setupRedis
+		setupNodejs
+		setupMemcached
+		setupNginx
+		setupMongodb
+		setupCutyCapt
+		setupGtkSharp
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "b" ]; then
+		echo "Installing Web Server ... [c,d]"
+		echo "------------------------------------"
+		setupMono
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "c" ]; then
+		setupMono
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "d" ]; then
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "e" ]; then
+		setupHaproxy
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "f" ]; then
+		setupRedis
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "g" ]; then
+		setupNodejs
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "h" ]; then
+		setupMongodb
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "i" ]; then
+		setupNginx
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "j" ]; then
+		setupMemcached
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "k" ]; then
+		setupCutyCapt
+		read -n 1 -p "Press <Enter> to continue..."
+	 
+	elif [ "$M" = "l" ]; then
+		setupGtkSharp
+		read -n 1 -p "Press <Enter> to continue..."
+
+	else
+		echo "Select Error!"
+		read -n 1 -p "Press <Enter> to continue..."
+	fi
+
+	selectCmd
 	return 0
 }
 
@@ -39,9 +119,9 @@ function setupNodejs()
 	yum -y install nodejs
 	echo "Install nodejs completed. info:"
 	node -v
-		
+
 	sudo echo "sudo npm install forever|mqtt|websocket|websocket-server|socket.io to '/wwwroot/node_mqtt'"
-	
+
 	sudo npm install forever -g
 	sudo npm install mqtt -g
 	sudo npm install websocket -g
@@ -163,7 +243,7 @@ function setupMemcached()
 
 function setupMono()
 {
-	yum -y install mono-*
+	#yum -y install mono-*
 	cd /tmp
 	wget http://download.mono-project.com/repo/xamarin.gpg
 	rpm --import xamarin.gpg
@@ -171,6 +251,8 @@ function setupMono()
 	yum -y install mono-complete
 	echo "Install mono completed. info:"
 	mono -V
+	
+	setupJws
 	
 	return 0
 }
@@ -414,84 +496,5 @@ function setupCutyCapt()
 	return 0
 }
 
-function selectCmd()
-{
-	alias cp='cp'
-	showMenu
-	echo "Please select a serial number for installation"
-	echo "When your manual installation, Please install the [d] first:"
-	echo "[f][g] be dependent on [e]:"
-	read -n 1 M
-	echo
-
-	if [ "$M" = "x" ]; then
-		exit 1
-	elif [ "$M" = "a" ]; then
-		 echo "Installing ALL... [d,e,g,h,k,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupMono
-		 setupJws
-		 setupMysql
-		 setupHaproxy
-		 setupRedis
-	elif [ "$M" = "b" ]; then
-		 echo "Installing Web Server ... [d,e,g,k,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupMono
-		 setupJws
-		 setupHaproxy
-		 setupRedis
-	elif [ "$M" = "c" ]; then
-		 echo "Installing MySQL ... [d,h,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupMysql
-		 setupRedis
-	elif [ "$M" = "d" ]; then
-		 setupLibs
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "e" ]; then
-		 setupMono
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "f" ]; then
-		 setupNodejs
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "g" ]; then
-		 setupJws
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "h" ]; then
-		 setupMysql
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "i" ]; then
-		 setupMemcached
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "j" ]; then
-		 setupNginx
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "k" ]; then
-		 setupHaproxy
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "l" ]; then
-		 setupRedis
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "m" ]; then
-		 setupCutyCapt
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "n" ]; then
-		 setupGtkSharp
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "o" ]; then
-		 setupMongodb
-     read -n 1 -p "Press <Enter> to continue..."
-	else
-		 echo "Select Error!"
-     read -n 1 -p "Press <Enter> to continue..."
-	fi
-
-	selectCmd
-	return 0
-}
 cd /tmp
 selectCmd
diff --git a/fedora-installScript b/fedora-installScript
--- a/fedora-installScript
+++ b/fedora-installScript
@@ -7,27 +7,124 @@
 
 function showMenu()
 {
+	setupLibs
 	clear
 	echo
 	echo "--------------------------------------------------------------"
 	echo "|      Fedora19/20 Install Helper                            |"
 	echo "|      copyright https://github.com/cjy37                    |"
 	echo "--------------------------------------------------------------"
-	echo "|      a. Install Web Server + MySQL [d,e,g,h,k,l]           |"
-	echo "|      b. Install Web Server   [d,e,g,k,l]                   |"
-	echo "|      c. Install MySQL    [d,h,l]                           |"
-	echo "|      d. Install Libs     [Public Libs]                     |"
-	echo "|      e. Install mono                                       |"
-	echo "|      g. Install jexus v5                                   |"
-	echo "|      h. Install mysql v5.5                                 |"
-	echo "|      j. Install nginx                                      |"
-	echo "|      k. Install haproxy                                    |"
-	echo "|      l. Install Redis                                      |"
+	echo "|      a. Install ALL                                        |"
+	echo "|      b. Install Web Server (linux mono mysql jexus)[c,d]   |"
+	echo "|      c. Install Mono & Jexus (Asp.Net Web Server)          |"
+	echo "|      d. Install Mysql (MariaDB-10)                         |"
+	echo "|      e. Install Haproxy                                    |"
+	echo "|      f. Install Redis                                      |"
+	echo "|      g. Install Node.js                                    |"
+	echo "|      h. Install MongoDB                                    |"
+	echo "|      i. Install Nginx                                      |"
 	echo "|      x. Exit                                               |"
 	echo "--------------------------------------------------------------"
 	echo
 	return 0
 }
+
+
+function selectCmd()
+{
+	alias cp='cp'
+	showMenu
+	echo "Please select a serial number for installation [a-x]:"
+	read -n 1 M
+	echo
+
+	if [ "$M" = "x" ]; then
+		exit 1
+		
+	elif [ "$M" = "a" ]; then
+		echo "Installing ALL..."
+		echo "------------------------------------"
+		setupMono
+		setupMysql
+		setupHaproxy
+		setupRedis
+		setupNodejs
+		setupNginx
+		setupMongodb
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "b" ]; then
+		echo "Installing Web Server ... [c,d]"
+		echo "------------------------------------"
+		setupMono
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "c" ]; then
+		setupMono
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "d" ]; then
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "e" ]; then
+		setupHaproxy
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "f" ]; then
+		setupRedis
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "g" ]; then
+		setupNodejs
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "h" ]; then
+		setupMongodb
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "i" ]; then
+		setupNginx
+		read -n 1 -p "Press <Enter> to continue..."
+
+	else
+		echo "Select Error!"
+		read -n 1 -p "Press <Enter> to continue..."
+	fi
+
+	selectCmd
+	return 0
+}
+
+function setupNodejs()
+{
+	yum -y install nodejs
+	echo "Install nodejs completed. info:"
+	node -v
+
+	sudo echo "sudo npm install forever|mqtt|websocket|websocket-server|socket.io to '/wwwroot/node_mqtt'"
+
+	sudo npm install forever -g
+	sudo npm install mqtt -g
+	sudo npm install websocket -g
+	sudo npm install websocket-server -g
+	sudo npm install socket.io@0.9 -g
+	sudo npm install log4js -g
+	sudo npm install pm2 -g --unsafe-perm
+	
+	return 0
+}
+
+function setupMongodb()
+{
+	yum -y install mongodb mongodb-server
+	echo "Install mongodb completed. info:"
+	mongod --version
+	
+	return 0
+}
+
 
 function setupLibs()
 {
@@ -47,6 +144,8 @@ function setupMono()
 	sudo yum -y install mono-complete
 	echo "Install mono completed. info:"
 	mono -V
+	
+	setupJws
 	
 	return 0
 }
@@ -160,71 +259,5 @@ function setupJws()
 	return 0
 }
 
-function selectCmd()
-{
-	alias cp='cp'
-	showMenu
-	echo "Please select a serial number for installation"
-	echo "When your manual installation, Please install the [d] first:"
-	echo "[f][g] be dependent on [e]:"
-	read -n 1 M
-	echo
-
-	if [ "$M" = "x" ]; then
-		exit 1
-	elif [ "$M" = "a" ]; then
-		 echo "Installing ALL... [d,e,g,h,k,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupLibgdiplus
-		 setupMono
-		 setupJws
-		 setupMysql
-		 setupHaproxy
-		 setupRedis
-	elif [ "$M" = "b" ]; then
-		 echo "Installing Web Server ... [d,e,g,k,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupLibgdiplus
-		 setupMono
-		 setupJws
-		 setupHaproxy
-		 setupRedis
-	elif [ "$M" = "c" ]; then
-		 echo "Installing MySQL ... [d,h,l]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupMysql
-		 setupRedis
-	elif [ "$M" = "d" ]; then
-		 setupLibs
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "e" ]; then
-		 setupMono
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "g" ]; then
-		 setupJws
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "h" ]; then
-		 setupMysql
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "j" ]; then
-		 setupNginx
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "k" ]; then
-		 setupHaproxy
-     read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "l" ]; then
-		 setupRedis
-     read -n 1 -p "Press <Enter> to continue..."
-	else
-		 echo "Select Error!"
-     read -n 1 -p "Press <Enter> to continue..."
-	fi
-
-	selectCmd
-	return 0
-}
 cd /tmp
 selectCmd
diff --git a/ubuntu-installScript b/ubuntu-installScript
--- a/ubuntu-installScript
+++ b/ubuntu-installScript
@@ -7,30 +7,108 @@
 
 function showMenu()
 {
+	setupLibs
 	clear
 	echo
 	echo "--------------------------------------------------------------"
 	echo "|      Ubuntu12.04 Install Helper                            |"
 	echo "|      copyright https://github.com/cjy37                    |"
 	echo "--------------------------------------------------------------"
-	echo "|      a. Install Web Server + MySQL [d,e,g,h,i,j]           |"
-	echo "|      b. Install Web Server   [d,e,g,i,j]                   |"
-	echo "|      c. Install MySQL    [d,h,j]                           |"
-	echo "|      d. Install Libs     [Public Libs]                     |"
-	echo "|      e. Install Mono (Last releases version)               |"
-	echo "|      f. *Update Jexus v5.5.3 (Mono Web Server)             |"
-	echo "|      g. Install Jexus v5.5.3 (Mono Web Server)             |"
-	echo "|      h. Install Mysql v5.5 (MariaDB)                       |"
-	echo "|      i. Install Haproxy                                    |"
-	echo "|      j. Install Redis                                      |"
-	echo "|      k. Install Node.js                                    |"
-	echo "|      l. Install MQTT Server                                |"
-	echo "|      m. Install MongoDB                                    |"
-	echo "|      n. Install Nginx                                      |"
-	echo "|      o. *Update Mono (After v3.6.0)                        |"
+	echo "|      a. Install ALL                                        |"
+	echo "|      b. Install Web Server (linux mono mysql jexus)[c,d]   |"
+	echo "|      c. Install Mono & Jexus (Asp.Net Web Server)          |"
+	echo "|      d. Install Mysql (MariaDB-10)                         |"
+	echo "|      e. Install Haproxy                                    |"
+	echo "|      f. Install Redis                                      |"
+	echo "|      g. Install Node.js                                    |"
+	echo "|      h. Install MongoDB                                    |"
+	echo "|      i. Install Nginx                                      |"
+	echo "|      j. Install MQTT Server                                |"
+	echo "|      k. *Update Mono & Jexus                               |"
+	echo "|      l. *Update Jexus (Mono Web Server)                    |"
 	echo "|      x. Exit                                               |"
 	echo "--------------------------------------------------------------"
 	echo
+	return 0
+}
+
+function selectCmd()
+{
+	alias cp='cp'
+	showMenu
+	echo "Please select a serial number for installation [a-x]:"
+	read -n 1 M
+	echo
+
+	if [ "$M" = "x" ]; then
+		exit 1
+		
+	elif [ "$M" = "a" ]; then
+		echo "Installing ALL..."
+		echo "------------------------------------"
+		setupNewMono
+		setupMysql
+		setupHaproxy
+		setupRedis
+		setupNodeJS
+		setupMQTTServer
+		setupMongoDB
+		setupNginx
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "b" ]; then
+		echo "Installing Web Server(linux mono mysql jexus) (lmmj) [c,d]"
+		echo "------------------------------------"
+		setupNewMono
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "c" ]; then
+		setupNewMono
+		read -n 1 -p "Press <Enter> to continue..."
+
+	elif [ "$M" = "d" ]; then
+		setupMysql
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "e" ]; then
+		setupHaproxy
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "f" ]; then
+		setupRedis
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "g" ]; then
+		setupNodeJS
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "j" ]; then
+		setupMQTTServer
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "h" ]; then
+		setupMongoDB
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "i" ]; then
+		setupNginx
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "k" ]; then
+		updateMono
+		read -n 1 -p "Press <Enter> to continue..."
+		
+	elif [ "$M" = "l" ]; then
+		updateJws
+		read -n 1 -p "Press <Enter> to continue..."
+
+	else
+		echo "Select Error!"
+		read -n 1 -p "Press <Enter> to continue..."
+	fi
+
+	selectCmd
 	return 0
 }
 
@@ -68,13 +146,19 @@ function setupLibs()
 
 function updateMono()
 {
-	echo "Update mono v3.8+"
+	echo "Update mono"
 	cd /tmp
 	wget http://download.mono-project.com/repo/xamarin.gpg
 	apt-key add xamarin.gpg
 	echo "deb http://download.mono-project.com/repo/debian wheezy main" > /etc/apt/sources.list.d/mono-xamarin.list
 	sudo apt-get update
 	sudo apt-get install -y mono-complete
+	echo "Install mono completed. info:"
+	mono -V
+	
+	updateJws
+	
+	return 0
 }
 
 function setupNewMono()
@@ -86,7 +170,7 @@ function setupNewMono()
 	  mkdir -pv /tmp/downloads
 	fi
 	
-	echo "Install mono v3.6+"
+	echo "Install mono"
 	echo "------------------------------------"
 
 	sudo apt-get -f remove -y libmono* mono-jay
@@ -104,6 +188,8 @@ function setupNewMono()
 	
 	echo "Install mono completed. info:"
 	mono -V
+	
+	setupJws
 	
 	return 0
 }
@@ -221,6 +307,8 @@ function setupNginx()
 	sudo apt-get update
 	sudo apt-get install nginx
 	echo "Nginx config file: /etc/nginx/nginx.conf"
+	
+	return 0
 }
 
 function updateJws()
@@ -247,8 +335,8 @@ function updateJws()
 	  echo "Jexus upgrade to path: /usr/jexus/"
 	  echo "Jexus config file (/usr/jexus/jws.conf and /usr/jexus/siteconf/*)"
 	fi
-	return 0
 	
+	return 0
 }
 
 function setupJws()
@@ -293,84 +381,5 @@ function setupJws()
 	return 0
 }
 
-function selectCmd()
-{
-	alias cp='cp'
-	showMenu
-	echo "Please select a serial number for installation"
-	echo "When your manual installation, Please install the [d] first:"
-	echo "[f][g] be dependent on [e]:"
-	read -n 1 M
-	echo
-
-	if [ "$M" = "x" ]; then
-		exit 1
-	elif [ "$M" = "a" ]; then
-		echo "Installing ALL... [d,e,g,h,i,j]"
-		echo "------------------------------------"
-		setupLibs
-		setupNewMono
-		setupJws
-		setupMysql
-		setupHaproxy
-		setupRedis
-	elif [ "$M" = "b" ]; then
-		echo "Installing Web Server ... [d,e,g,i,j]"
-		echo "------------------------------------"
-		setupLibs
-		setupNewMono
-		setupJws
-		setupHaproxy
-		setupRedis
-	elif [ "$M" = "c" ]; then
-		 echo "Installing MySQL ... [d,h,j]"
-		 echo "------------------------------------"
-		 setupLibs
-		 setupMysql
-		 setupRedis
-	elif [ "$M" = "d" ]; then
-		setupLibs
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "e" ]; then
-		setupNewMono
-		read -n 1 -p "Press <Enter> to continue..."
-        elif [ "$M" = "f" ]; then
-		updateJws
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "g" ]; then
-		setupJws
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "h" ]; then
-		setupMysql
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "i" ]; then
-		setupHaproxy
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "j" ]; then
-		setupRedis
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "k" ]; then
-		setupNodeJS
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "l" ]; then
-		setupMQTTServer
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "m" ]; then
-		setupMongoDB
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "n" ]; then
-		setupNginx
-		read -n 1 -p "Press <Enter> to continue..."
-	elif [ "$M" = "o" ]; then
-		updateMono
-		read -n 1 -p "Press <Enter> to continue..."
-	else
-		echo "Select Error!"
-		read -n 1 -p "Press <Enter> to continue..."
-	fi
-
-	selectCmd
-	return 0
-}
 cd /tmp
 selectCmd
